# Generated by Django 3.0.5 on 2020-05-01 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Task_App', '0002_tasklist_manage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='manage',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='taskuser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
