# Generated by Django 3.0.5 on 2020-05-01 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task_App', '0003_auto_20200501_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='taskuser',
        ),
    ]
